-- بوابة قرية الحرية — مخطط Supabase للإصدار النهائي
create table if not exists public.announcements(id bigint generated by default as identity primary key,title text not null,description text,priority text not null default 'normal' check(priority in('normal','urgent')),published boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.services(id bigint generated by default as identity primary key,title text not null,description text,category text not null,phone text,location text,published boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.complaints(id bigint generated by default as identity primary key,type text not null,body text not null,status text not null default 'new' check(status in('new','reviewing','closed')),created_at timestamptz not null default now());
create table if not exists public.activity_logs(id bigint generated by default as identity primary key,actor_role text,action text not null,table_name text,record_id bigint,created_at timestamptz not null default now());
create table if not exists public.settings(key text primary key,value text,updated_at timestamptz not null default now());
create table if not exists public.categories(id bigint generated by default as identity primary key,name text unique not null,icon text default '📍',enabled boolean not null default true,sort_order int not null default 0);
create table if not exists public.notifications(id bigint generated by default as identity primary key,title text not null,body text,published boolean not null default true,urgent boolean not null default false,created_at timestamptz not null default now());
create index if not exists announcements_created_at_idx on public.announcements(created_at desc);
create index if not exists services_category_idx on public.services(category);
create index if not exists complaints_created_at_idx on public.complaints(created_at desc);

alter table public.announcements enable row level security;
alter table public.services enable row level security;
alter table public.notifications enable row level security;
alter table public.categories enable row level security;
alter table public.complaints enable row level security;
alter table public.activity_logs enable row level security;
alter table public.settings enable row level security;

drop policy if exists "public read announcements" on public.announcements;
create policy "public read announcements" on public.announcements for select to anon,authenticated using(published=true);
drop policy if exists "public read services" on public.services;
create policy "public read services" on public.services for select to anon,authenticated using(published=true);
drop policy if exists "public read notifications" on public.notifications;
create policy "public read notifications" on public.notifications for select to anon,authenticated using(published=true);
drop policy if exists "public read categories" on public.categories;
create policy "public read categories" on public.categories for select to anon,authenticated using(enabled=true);
-- لا توجد سياسات عامة للكتابة. كل عمليات الإدارة تمر عبر Edge Function باستخدام service_role.

insert into public.categories(name,icon,sort_order) values
('مساجد','🕌',1),('مدارس','🏫',2),('صحة','🏥',3),('طوارئ','🚑',4),('بقاليات','🛒',5),('أفران','🥖',6),('صيدليات','💊',7),('أطباء','🩺',8),('مهن وخدمات','🛠️',9),('مواصلات','🚐',10),('خدمات عامة','🏘️',11)
on conflict(name) do nothing;
