window.SUPABASE_READY=false;window.sb=null;window.CLOUD_SESSION=localStorage.getItem('qaryahurriya_session')||'';
async function initSupabase(){const c=window.APP_CONFIG||{};if(!c.SUPABASE_URL||!c.SUPABASE_ANON_KEY||!window.supabase)return false;try{window.sb=window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_ANON_KEY);window.SUPABASE_READY=true;return true}catch(e){console.error(e);return false}}
async function cloudRead(){if(!window.sb)return null;const q=async(t)=>{const r=await sb.from(t).select('*').eq('published',true).order('created_at',{ascending:false});if(r.error)throw r.error;return r.data||[]};const [a,s]=await Promise.all([q('announcements'),q('services')]);let complaints=[];if(window.currentRole==='admin')try{const r=await edgeCall('list_complaints',{});complaints=r.complaints||[]}catch(e){}return {announcements:a.map(x=>({id:x.id,title:x.title,desc:x.description,priority:x.priority,date:(x.created_at||'').slice(0,10)})),services:s.map(x=>({id:x.id,title:x.title,desc:x.description,category:x.category,phone:x.phone,location:x.location})),complaints}}
async function edgeCall(action,data){const url=(window.APP_CONFIG||{}).EDGE_FUNCTION_URL;if(!url)throw Error('EDGE_FUNCTION_URL missing');const headers={'Content-Type':'application/json','apikey':(window.APP_CONFIG||{}).SUPABASE_ANON_KEY||''};if(window.CLOUD_SESSION)headers.Authorization='Bearer '+window.CLOUD_SESSION;const r=await fetch(url,{method:'POST',headers,body:JSON.stringify({action,...data})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'تعذر تنفيذ العملية');return j}
async function cloudLogin(code){const j=await edgeCall('login',{code});if(j.token){window.CLOUD_SESSION=j.token;localStorage.setItem('qaryahurriya_session',j.token)}return j}
async function cloudSave(table,obj,id){return edgeCall('upsert',{table,id:id||null,data:table==='announcements'?{title:obj.title,description:obj.desc,priority:obj.priority,published:true}:{title:obj.title,description:obj.desc,category:obj.category,phone:obj.phone,location:obj.location,published:true}})}
async function cloudDelete(table,id){return edgeCall('delete',{table,id})}
async function cloudComplaint(type,body){return edgeCall('create_complaint',{type,body})}
async function cloudComplaintStatus(id,status){return edgeCall('update_complaint',{id,status})}
async function tryCloud(){const ok=await initSupabase();const el=document.getElementById('cloudStatus');if(ok){el.textContent='☁️ اتصال Supabase مفعّل';try{await syncCloud()}catch(e){console.warn(e)}}else el.textContent='📱 الوضع المحلي — جاهز للعمل'}
